name: riverpod_offline
description: Persist riverpod state offline using Hive
version: 1.0.0
repository: https://github.com/gabsn/riverpod_offline

environment:
  sdk: ^3.0.5

dependencies:
  easy_debounce: ^2.0.3
  hive: ^2.2.3
  hooks_riverpod: ^2.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
